# 本文件由 packages/contracts/scripts/generate.mjs 生成 —— 请勿手工编辑。
# 来源：packages/contracts/schema/v1/citation.schema.json

# generated by datamodel-codegen:
#   filename:  citation.schema.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Citation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sourceName: Annotated[str, Field(max_length=200, min_length=1)]
    """
    来源的人类可读名称，例如某个开放许可词典或用户自己的文档名。
    """
    sourceVersion: Annotated[str, Field(max_length=100, min_length=1)]
    """
    来源版本；无版本时写显式占位值，不得省略。
    """
    sourceLocator: Annotated[str, Field(max_length=500, min_length=1)]
    """
    可定位坐标：页码/段落/条目 id 等。用户必须能据此回到原文核对。
    """
    licenseLabel: Annotated[str, Field(max_length=200, min_length=1)]
    """
    许可标识。未获书面离线授权的来源不得声称可离线索引（Q1 红线）。
    """
