# 本文件由 packages/contracts/scripts/generate.mjs 生成 —— 请勿手工编辑。
# 来源：packages/contracts/schema/v1/envelope.schema.json

# generated by datamodel-codegen:
#   filename:  envelope.schema.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal[
        'ENGM.CONTRACT.INVALID_INPUT',
        'ENGM.CONTRACT.SCHEMA_INVALID',
        'ENGM.CONTRACT.VERSION_MISMATCH',
        'ENGM.INTERNAL.UNEXPECTED',
    ]
    message: Annotated[str, Field(max_length=500, min_length=1)]
    retryable: bool
    details: Any | None = None


class Citation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sourceName: Annotated[str, Field(max_length=200, min_length=1)]
    sourceVersion: Annotated[str, Field(max_length=100, min_length=1)]
    sourceLocator: Annotated[str, Field(max_length=500, min_length=1)]
    licenseLabel: Annotated[str, Field(max_length=200, min_length=1)]


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    inputTokens: Annotated[int, Field(ge=0)]
    outputTokens: Annotated[int, Field(ge=0)]
    cached: bool


class Success(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ok: Literal[True]
    requestId: Annotated[str, Field(max_length=128, min_length=1)]
    """
    请求标识，用于日志与故障定位配对。空字符串等同于缺失。
    """
    data: Any
    citations: list[Citation]
    """
    该回答依据的来源列表。没有依据时必须是空数组，而不是省略字段——省略会让"无来源"和"忘了带"无法区分。
    """
    usage: Usage | None = None


class Failure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ok: Literal[False]
    requestId: Annotated[str, Field(max_length=128, min_length=1)]
    error: Error


class LocalResponse(RootModel[Success | Failure]):
    root: Annotated[Success | Failure, Field(title='LocalResponse')]
    """
    所有边界上的统一响应信封（SPEC-M00 §5.2 / B-6）。成功与失败两种形态由 ok 判别：成功必须带 data、不得带 error；失败必须带 error、不得带 data。刻意不使用跨文件 $ref —— 三个校验器（TS/Python/Rust）都只编译单份文档，避免多文档引用解析差异成为三方不一致的来源；$defs 中 error 与 citation 的形状与 error.schema.json、citation.schema.json 行为等价，由 packages/contracts/tests/fixtures 的共享正反例同时压两份文档来保证。
    """
