# 本文件由 packages/contracts/scripts/generate.mjs 生成 —— 请勿手工编辑。
# 来源：packages/contracts/schema/v1/error.schema.json

# generated by datamodel-codegen:
#   filename:  error.schema.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class ContractError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal[
        'ENGM.CONTRACT.INVALID_INPUT',
        'ENGM.CONTRACT.SCHEMA_INVALID',
        'ENGM.CONTRACT.VERSION_MISMATCH',
        'ENGM.INTERNAL.UNEXPECTED',
    ]
    """
    已注册的错误码。取值集合与 error-codes.json 的 codes 键完全一致。
    """
    message: Annotated[str, Field(max_length=500, min_length=1)]
    """
    给人看的说明。不得回显用户正文或密钥。
    """
    retryable: bool
    """
    调用方是否可以原样重试。业务校验失败一律为 false，避免无限自修复。
    """
    details: Any | None = None
    """
    附加诊断信息。结构由产生方决定，但不得包含用户正文、完整提示词或凭据。
    """
