# 本文件由 packages/contracts/scripts/generate.mjs 生成 —— 请勿手工编辑。
# 来源：packages/contracts/schema/v1/job.schema.json

# generated by datamodel-codegen:
#   filename:  job.schema.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class Progress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    completed: Annotated[int, Field(ge=0)]
    """
    已完成的工作单元数。
    """
    total: Annotated[int, Field(ge=0)]
    """
    总工作单元数。0 表示总数仍未知，而不是"没有工作"。
    """
    message: Annotated[str | None, Field(max_length=200)] = None
    """
    给用户看的阶段说明。不得包含用户正文。
    """


class Job(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    jobId: Annotated[str, Field(max_length=128, min_length=1)]
    """
    任务标识。同一 jobId 的重复请求必须幂等（B-7）。
    """
    status: Literal['pending', 'running', 'succeeded', 'failed', 'cancelled']
    """
    任务状态。pending/running 为进行中，succeeded/failed/cancelled 为终态。
    """
    progress: Progress
    cancelRequested: bool
    """
    调用方是否已请求取消。
    """
