# 本文件由 packages/contracts/scripts/generate.mjs 生成 —— 请勿手工编辑。
# 来源：packages/contracts/schema/v1/version.schema.json

# generated by datamodel-codegen:
#   filename:  version.schema.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class SchemaId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern='^https://engmentor\\.local/contracts/v1/[a-z][a-z0-9-]*\\.(schema\\.json|json)$'
        ),
    ]


class ContractVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contractVersion: Annotated[str, Field(pattern='^v[0-9]+(\\.[0-9]+)*$')]
    """
    契约大版本，形如 v1、v1.1。字段一旦冻结只能通过新增大版本演进（§5.2）。
    """
    schemaIds: Annotated[list[SchemaId], Field(min_length=1)]
    """
    该实现嵌入的 schema $id 集合。与 schema-manifest.json 的清单比对，防止某一侧落后于契约包（§5.3 第 6 条）。
    """
